name: Build and test .NET EventGenerator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore NuGet packages
      run: dotnet restore EventsGenerator/EventsGenerator.csproj
    - name: Build
      run: dotnet build --no-restore EventsGenerator/EventsGenerator.csproj
  
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Testing
      run: dotnet test EventsGenerator.Tests/EventsGenerator.Tests.csproj
    